### PR TITLE
⚠️ Rename the API group from metal3.io to ironic

### PR DESCRIPTION
**Pull request by dtantsur**
Initially, I used metal3.io like BMO does, but it does not look correct
and causes absurd results when operator-sdk is used. We were not
supposed to duplicate the domain in the group.

Signed-off-by: Dmitry Tantsur <dtantsur@protonmail.com>

### CODE REVIEW

**Comment by dtantsur** [comment]
/hold

I'm still not 100% sure

**Comment by tuminoid** [comment]
/cc @kashifest 
PTAL and express opinion as well.

**Comment by dtantsur** [comment]
/hold cancel

See also https://groups.google.com/u/1/g/metal3-dev/c/8ez2LCM9cng

**Review by tuminoid — COMMENTED** [review]
/approve

**Pull request merged**
