### PR TITLE
✨ Implement version picker for Ironic

### PR DESCRIPTION
**Pull request by dtantsur**
The Ironic object now has a Version field that allows a user to request
a specific version (latest or X.Y). Version 27.0 is added as supported.

The Status is updated to support both installed and requested version
(removing redundant nested structure).

Signed-off-by: Dmitry Tantsur <dtantsur@protonmail.com>

### CODE REVIEW

**Review by lentzi90 — APPROVED** [review]

**Review by tuminoid — COMMENTED** [review]
Besides the typo nit already mentioned, looks clean to me.
/hold
Holding in case you want to fix typo now or unhold for later.

/approve

**Pull request merged**
