### PR TITLE
Add an environment file and a configmap to customize the manager

### PR DESCRIPTION
**Pull request by dtantsur**
Doing so simplifies downstream customizations, e.g. in metal3-dev-env:
https://github.com/metal3-io/metal3-dev-env/pull/1466.

Signed-off-by: Dmitry Tantsur <dtantsur@protonmail.com>

### CODE REVIEW

**Comment by matthewei** [comment]
Hi @dtantsur ,If do that and we have to delete the pod to update the env. Is it really a good way?

**Review by Rozzii — COMMENTED** [review]
/lgtm

**Comment by dtantsur** [comment]
> If do that and we have to delete the pod to update the env. Is it really a good way?

You're not forced to use the new configmap. This is primarily for consistency with how BMO is configured in its manifests, which in turn will facilitate the effort to add IrSO to metal3-dev-env.

**Comment by matthewei** [comment]
> > If do that and we have to delete the pod to update the env. Is it really a good way?
> 
> You're not forced to use the new configmap. This is primarily for consistency with how BMO is configured in its manifests, which in turn will facilitate the effort to add IrSO to metal3-dev-env.

I see

**Pull request merged**
