### PR TITLE
Fix HA feature gate applied unconditionally

### PR DESCRIPTION
**Pull request by dtantsur**
Follow-up to c9b50fd46f56a95fb614ccbfaeef93fa5d69f845.

Finally write some unit tests for validation (more TODO).

Signed-off-by: Dmitry Tantsur <dtantsur@protonmail.com>

### CODE REVIEW

**Review by iurygregory — COMMENTED** [review]
lgtm

**Review by tuminoid — COMMENTED** [review]
/lgtm

**Review by Rozzii — COMMENTED** [review]
/approve

**Pull request merged**
