### PR TITLE
⚠️ Rework naming of references in the API

### PR DESCRIPTION
**Pull request by dtantsur**
As discussed in
https://github.com/metal3-io/ironic-standalone-operator/issues/91, lets
use simpler reference names and reserve the SomethingRef format for when
the field can refer to different kinds or at least namespaces.

This is quite a breaking change but I don't see a lot of value in going
through deprecation since it's going to significantly complicate the
code nobody should be using in production yet.

Closes: #91 
Signed-off-by: Dmitry Tantsur <dtantsur@protonmail.com>

### CODE REVIEW

**Comment by dtantsur** [comment]
/hold

I'll create a corresponding metal3-dev-env change.

**Comment by dtantsur** [comment]
https://github.com/metal3-io/metal3-dev-env/pull/1478 pins IrSO to avoid breaking metal3-dev-env with this.

**Comment by tuminoid** [comment]
> This is quite a breaking change but I don't see a lot of value in going through deprecation since it's going to significantly complicate the code nobody should be using in production yet.

We absolutely should not make life difficult for ourselves here, this is pre-MVP.

**Review by tuminoid — COMMENTED** [review]
Looks much cleaner to me.

/approve

**Comment by elfosardo** [comment]
best do a change like this now

/lgtm

**Pull request merged**
