### PR TITLE
Fix Networking.ipAddress webhook's bug

### PR DESCRIPTION
**Pull request by matthewei**
Closes: https://github.com/metal3-io/ironic-standalone-operator/issues/60

### CODE REVIEW

**Comment by matthewei** [comment]
@dtantsur  Please

**Comment by iurygregory** [comment]
looks good, just wondering if would be good to have a test for this.

**Comment by matthewei** [comment]
> looks good, just wondering if would be good to have a test for this.

I will try it.

**Comment by matthewei** [comment]
> looks good, just wondering if would be good to have a test for this.

@iurygregory Hi, I would like to raise a new PR for your request.

**Comment by dtantsur** [comment]
/approve
/lgtm

We need to have unit tests for the validations but we currently don't. Help welcome.

**Pull request merged**
