### PR TITLE
Fix markdownlint issues

### PR DESCRIPTION
**Pull request by Rozzii**
This commit:
- Aligns the .md files with the markdownlint requirements.

### CODE REVIEW

**Comment by Rozzii** [comment]
/hold
First need to merge https://github.com/metal3-io/ironic-standalone-operator/pull/14

**Review by tuminoid — COMMENTED** [review]
LGTM, but we should be holding it to be merged only after Prow PR is merged, so we can see it passes.

/hold

**Review by tuminoid — APPROVED** [review]
Thanks @rozzii!

LGTM

**Pull request merged**
